name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        sh -e /etc/init.d/xvfb start
      timeout: 10m
    - name: Run Selenium Tests
      run: |
        mvn test  # Replace with the actual command to run your tests
      env:
        CHROME_BIN: /usr/bin/chromium-browser

